### PR TITLE
Fixed quote escaping

### PR DESCRIPTION
**Pull request by Joannis**

### CODE REVIEW

**Review by tanner0101 — APPROVED** [review]
great!

**Review by vzsg — DISMISSED** [review]
This line doesn't compile on Linux though...

**Comment by tanner0101** [comment]
We need to use `characters.count` for Swift < 4 @Joannis

**Comment by Joannis** [comment]
Whoops! I'll fix that.

**Comment by tanner0101** [comment]
```
/home/ubuntu/json/Sources/JSON/JSON+Serialize.swift:45:21: error: type 'String' does not conform to protocol 'Sequence'
        for char in self {
```

@Joannis need `.characters` there too >_<

**Comment by Joannis** [comment]
I should really set up Swift 3.1 again 😬

**Review by tanner0101 — APPROVED** [review]

**Pull request merged**
